load("@rules_cc//cc:defs.bzl", "cc_import", "cc_library")

package(default_visibility = ["//visibility:private"])

_COMPATIBLE_WITH = [
    "@platforms//cpu:{CPU}",
    "@platforms//os:linux",
]

_HEADERS = glob(
    ["payload/usr/include/dash_api/*.h"],
    allow_empty = False,
)

cc_import(
    name = "_dashapi_dso",
    shared_library = "payload/usr/lib/libdashapi.so",
    target_compatible_with = _COMPATIBLE_WITH,
)

cc_library(
    name = "dashapi",
    hdrs = _HEADERS,
    includes = ["payload/usr/include"],
    target_compatible_with = _COMPATIBLE_WITH,
    visibility = ["//visibility:public"],
    deps = [":_dashapi_dso"],
)

filegroup(
    name = "prebuilt_files",
    srcs = _HEADERS + [
        "IMPORTS.json",
        "payload/usr/lib/libdashapi.so",
        "{DEB_FILENAME}",
    ],
    target_compatible_with = _COMPATIBLE_WITH,
    visibility = ["//visibility:public"],
)

filegroup(
    name = "shared_library",
    srcs = ["payload/usr/lib/libdashapi.so"],
    target_compatible_with = _COMPATIBLE_WITH,
    visibility = ["//visibility:public"],
)
