"""DASH protobuf sources covered by generation and package validation."""

PROTO_FILES = [
    "proto/acl_group.proto",
    "proto/acl_in.proto",
    "proto/acl_out.proto",
    "proto/acl_rule.proto",
    "proto/appliance.proto",
    "proto/eni.proto",
    "proto/eni_route.proto",
    "proto/ha_scope.proto",
    "proto/ha_scope_config.proto",
    "proto/ha_scope_state.proto",
    "proto/ha_set.proto",
    "proto/ha_set_config.proto",
    "proto/ha_set_state.proto",
    "proto/meter.proto",
    "proto/meter_policy.proto",
    "proto/meter_rule.proto",
    "proto/outbound_port_map.proto",
    "proto/outbound_port_map_range.proto",
    "proto/pa_validation.proto",
    "proto/prefix_tag.proto",
    "proto/qos.proto",
    "proto/route.proto",
    "proto/route_group.proto",
    "proto/route_rule.proto",
    "proto/route_type.proto",
    "proto/routing_appliance.proto",
    "proto/tunnel.proto",
    "proto/types.proto",
    "proto/vnet.proto",
    "proto/vnet_mapping.proto",
]
